name: PR Automatic Comment

on:
  pull_request:
    types: [opened]

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add comment to PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            const repo = context.repo;
            
            const commentBody = `
            👋 Thanks for opening this pull request!
            
            Your PR will be reviewed shortly. In the meantime, please make sure:
            - [ ] Tests are passing
            - [ ] Documentation is updated
            - [ ] Code follows project style guidelines
            
            If you have any questions, feel free to ask in this thread.
            `;
            
            await github.rest.issues.createComment({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: prNumber,
              body: commentBody
            });
            
            console.log(`Comment added to PR #${prNumber}`);
